# Copyright 2023 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      https://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Constants used across multiple files.
"""

TIME_REGEXP = "%Y-%m-%dT%H:%M:%S.%f%z"
WORKER_GROUP_PREFIX = "Slice-Worker "

REGEX_SUBSTR_MATCH_ROW_HEADERS = {
    "Some workers didn't report an error after ": "Node pool error",
    "checkpoint": "Checkpoint",
    "BAD_ICI": "BAD_ICI",
    "last_finished_run_id updated to": "Info",
    "MegaScale Topology Discovery in progress. Missing hosts ": (
        "Missing hosts in Topology discovery"
    ),
    "Enqueueing program \\d+: [a-z0-9]+ to continuation queue": "Info",
    "Failed to call GetSessioInfo for worker": "Failed to call GetSessioInfo",
    "failed to connect to all addresses": "Failed to connect",
    "MegaScale Topology Discovery": "MegaScale Topology Discovery",
}

REDUNDANT_LOGS_SUBSTR_MATCH = [
    "Sending to [0-9.]+:\\d+ on interface",
    "Created \\d+ channels for \\d+ interfaces on slice",
    "^argv\\[\\d+\\]: '",
    "Worker Address: [a-z0-9-_.]+:\\d+",
    "Starting launch_id for device_set_hash",
    "Constructing tf.data.Dataset",
    "Creating directories: ",
    "Driver opened.",
    "Applying remat on ",
    "All instances are ready for",
    "CallbackRegistryLogger dumping to file",
    "All directories created",
    "Created communicator.",
    "Received topology discovery response: go/debugonly",
    "Sending topology discovery request: go/debugonly",
    "gRPC experiments",
    "Load dataset info from",
    "Keeping the one from code.",
    "Registering error handler with name",
    "Found \\d+ TPU .* chips.",
    "Starting JAX distributed service on",
    "Connecting to JAX distributed service on ",
    "Using enhanced global barrier with ",
    "Using \\d+ from .* as SliceBuilder worker service port.",
    "Running on GCE, using service account ",
    "Using MXLA graph seed: ",
    "Creating client for slice \\d+ host \\d+",
    "Created Megascale GrpcTransport.",
    "Done allocating premapped memory of size",
    "HostCommandHandler will auto insert launch_ids ",
    "Created a HostCommandScheduler ",
    "Shapes to compress: ",
    "Prefixes to compress: ",
    "Fiber init: ",
    "Constraining input_batch",
    "feed_read_config=",
    "Starting AllocatorStats Reporter with reporting interval",
    "Done premapping memory of size ",
    "\\(HLO module .*\\): Executable fingerprint",
    "\\(HLO module .*\\): Host transfer fingerprint",
    "LatencyHidingScheduler current memory usage: ",
    "LIBTPU_INIT_ARGS='-",
    "Devices: \\[MegaScalePjRtDevice\\(",
    "DATA_DIR=gs:",
    "Successful retry compilation of fusion.",
    "Megascale init launch counter for ",
    "bytes for BuildID, using \\d+ syscalls.",
    "Creating numa aware allocators, number of NUMA nodes ",
    "Creating a tf.data.Dataset reading ",
    "Successfully started Runtime Metric Service on port",
    "Finished waiting at barrier for process",
    "Successfully started ICI network session with ",
    "Session master notifies the worker in a new session",
    "TPU premapped buffer enabled.",
    "tpu::System initialized",
    "CreateTpuSystemState: TPU initialization is successful",
    "CreateTpuSystemState: using TPU host premapped buffer of size",
    "Megascale Topology Coordinator started for ",
    "Ran \\d+ additional passes of layout assignment to assign all layouts.",
    "Skipping initialization of PA bits on",
    "Creating TpunetdClient with topology go/debugonly",
    "Connecting to vbar control service at ",
    "input_batch=",
    "gpt_trainer process   \\d+ step        0",
    "gpt_trainer process   \\d+ step       -1",
    "Using hybrid mesh shape: HybridMeshShape",
    "Inferred inter-slice/granule mesh shape",
    "param_.* = ",
    "multiply.* = multiply",
    "exponential.* = exponential",
    "FLOPS: ",
    "Temp memory: ",
    "fusion.* = fusion",
    "bitcast.* = bitcast",
    "Branch Divergence (Control Flow Processing)",
    "convolution.* = convolution",
    "tag: \\d+$",
    "pc: \\d+$",
    "chip_id: \\d+$",
    "tpu_core_summary {",
    "launch_ids {",
    "key: \\d+$",
    "value: \\d+$",
    "rapid_eye_info {",
    "telemetry {",
    "graph_events {",
    "graph_id: \"",
    "event_type: START",
    "timestamp_ns: \\d+$",
    "File \".*, line \\d+ in",
    "^ *}$",
    "^ *{$",
    "files.* % Done.*Copying",
    "e2e_time_us: \\d+$",
    "launch_id: \\d+$",
    "model.decoder.*: ",
    "mesh_rules.*:",
    "mesh_shape: ",
    "learner.optimizer.args.*:",
    "input\\..*:",
    "address: \"",
    "addresses {",
    "address_mappings {",
    "executable_fingerprint:",
    "pending_graphs {",
    "^ *actions {$",
    "^ *network_receive {$",
    "buffer_size: \\d+$",
    "num_outputs: \\d+$",
    "device_to_host {",
    "pending_actions: \\d+$",
    "host_id: \\d+$",
    "inputs {$",
    "destination {$",
    "transfer_info {$",
]

REDUNDANT_LOGS_EXACT = [
    (
        "All instances are ready for PRE_START_SESSION_BARRIER, broadcasting"
        " notification..."
    ),
    "CallbackRegistryLogger has log capacity of 0.",
    "Received topology discovery response: go/debugproto",
    "Initializing MegaScale transport.",
    "MegaScale transport initialized.",
    "=== Source Location Trace: ===",
    "TPU backend connection test passed!",
    "UptimeMetric attributes are updated.",
    "Using IP addresses for interface discovery.",
    "Session manager starting a new session...",
    "Creating TpunetdClient with topology go/debugproto",
    "Skipping initialization of PA bits on {type = TensorCore, index = 0}",
    "Using auto-detected TPU version TPU v6 lite",
    "--tpu_use_tfrt not specified. Using default value: true",
    "Running in Cloud, using TpunetdClient",
    "Premapped buffer is using alignment 64",
    "Starting premapped memory manager initialization...",
    "Registered plugin from module: breakpoint_debugger_server",
    "Starting a new ICI network session...",
    "Intentionally not binding to interface since server is client.",
    "Waiting for previous serialization to finish",
    "Not using TPUDecoding because is_decoding=False.",
    "MegaScale transport init succeeded.",
    "RAW: Futex::Swap(): using GFUTEX_SWAP",
    "Skipping MDS query due to true",
    "Starting gRPC Server.",
    "Resetting impairments.",
    "Remote crash gathering hook installed.",
    "Modified Input.config according to input_batcher:",
    "Waiting for previous serialization to finish.",
    "xla_tpu_autofdo_profile_dir updated to ",
    (
        "xla_tpu_autofdo_use_remote_repo is overridden to false because"
        " xla_tpu_autofdo_profile_dir is not set."
    ),
    "No recorder type specified, skipping initialize().",
    "Using TPUSplashAttention.",
    "ReadGlobalTimeCounter returning real data",
    "Session manager started the new session.",
    "Session master starting a new session...",
    "Session master started the new session.",
    "======= Memory Analysis ==================================",
    "TPU backend connection test passed! ",
    "Building device mesh.",
    "Building multi-slice/granule device mesh over axis 1.",
    "Building synchronization state...",
    "Starting synchronization...",
]

REDUNDANT_SEVERITY_IN_FILES = {
    "2a886c8_compiler_base.cc": "INFO",
    "b295d63588a.cc": "INFO",
    "megascale_context.cc": "INFO",
    "param_init.py": "INFO",
    "serialization.py": "INFO",
}
